apiVersion: ENC[AES256_GCM,data:ScI=,iv:LnRxnM/9NSPfmyxs79AesNq6T3mzPbGRqbsoOPBGnuQ=,tag:6m9y3BunvsjdH/KZpbyYrA==,type:str]
kind: ENC[AES256_GCM,data:9HKdKXJR,iv:8AsatVOD3Uwvh9AClywTWwa0Mnrm8T0f12IcgszZ4ig=,tag:iXJRfM24/jgbQKQQMffLgw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2seRDOoExsnt+3ZGww==,iv:zfro+CZ8arAlFishOqhEjMoInoyEJ8trJ0Tq/ywg3h8=,tag:9wzw+JKlHEIJhlnPK4Iywg==,type:str]
    namespace: ENC[AES256_GCM,data:U/eFuw==,iv:L44dWs892q1ql9/wqScvx40gd0kmqRNxGroBFe4Z3As=,tag:CmyTgU5MW1p8qW3SD0ulYQ==,type:str]
type: ENC[AES256_GCM,data:EMLTzvtN,iv:pxnSFEhzNppLAm2NBKBLM96qEvHPORtKmn7rqGdtMvY=,tag:SUeIqIS1O9yOaJV4Kj6fhA==,type:str]
stringData:
    immich.yaml: ENC[AES256_GCM,data:JIK7h5MfUnMlAcDfIa9L0P8UxDrM3GAbjbxL//JsN0+qlvGIYYGZA2Zx4egflURtb5xGXlWX6tUlN80BiVg3P32ZEkhFWsIvDxtELlQONMt68z5q75t3BfJ3TTDeLb26ypTO4+ObGM/sffpCLKWmXXHh7Bqmkv9nadVsSBF1nQhhckK7tIO3DFByUZCfwskexQ+GzNHtmj2ObuZ2ChR8rHj/xis98vvVInFf+vPOb/S+zHvH3NnQlZLCVnhA2IFSQg6d1O28gwZGbrjSnblsSo4jm1erHGIPZSzkQ+IS2l2YZnm/O/SW75DsEYzOBAum8P5SSrxpemNXxXzzfh1wFUfQtXujj46qLXhWYjyhbXcSsygz7VTagAwyOs3emp/7pPpCTFhUUewfj13yt6/e3VvhwswUCWgMOj8erOcz7FKsXeVquqsL6Kk4k8gsqeLv1kAVmJ1jLQKEzXkeM8Ai2y1FRkqHOYQa9j/V24Zx7Qw72IGWNGcnE9pIvcmMWIstpi54JdykG/O7ZwUG4kvl8MWB7YO3SOJJiCepMmDbWyofgOEYvXvXA/X+RWYGpD1fPNI9lnF308AGg76FW/FtbzYgldLh/3TVblLOvjnBvcdCVp42OVggcvoYV1f+7jVU9kqFdVXifRZC2TMjyDLtmC8/492P0Vlqf5ItBuGCa71xZ3Kzu4xkLH+Y4PxlzNLv4F4gnt8BFGU67rg5I6zF/T6I8xXvJ4YOk6k4250c4bnk0SHDcSYYC7iSsIOSRwffgIrsxrn/hmpzlHckatd+GYfGpdu77Wuv70LauBjVapn41m+78mcM6OifLq6hmyODGPqwciUrqOTsZns7jjWXWxGcgRgHx1xJO9G0ejXAP/TKcFr3inKuVyhGnkflgGSxn0AHJQ5m5AplrnKL08BJQa85gDB7IS1rYOwq5rX4nUmdwg5m0d5gmYHiWMzK3RgIMky9YvjQ3PA7QIMkQPReouJzjAXHX+RHkh4mxldCE4xry7GVA2IzjV17zIMnLlqfeb+HMaEbjUwaM5wE23+zUCf3v9hdb+B9KNofC1Gfdpvltw==,iv:eaW6WO0b3wZiY7SY4smvqEiEq/I7koTbgMgttjK17sk=,tag:Z4iFXpaebPlK9v9C5YsMiw==,type:str]
sops:
    age:
        - recipient: age1dhdj62dpal4r3kyy3v0g7d6cpupye3g33r5pl4csngs4fkh94eeqzn8puy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaTlPbkZYSnVBVmg2NUdr
            clJ2ckRVQnl0anJiNUtwWjdHVkEyc3hYSFRnCmxkQk9qMFVoMnRGcHI1M0hPN3U2
            MVpCVFpyc0Q3K1hpUXVFUUhaSXR5azgKLS0tIE1yVkNOdXhlMDBqellzMU1iUUxZ
            WFBzVFExUFhXNUVKdGhVdlB4WWpmbnMK843N/MCkjZ6pMTbrTB8A7aJPsBmQtyBn
            9zV+2T1erXTRN8ADnIWtKPID4kxsF33sc8bgerwVaf3g9+uOqU3I9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-08T22:47:32Z"
    mac: ENC[AES256_GCM,data:6YyzlpamokezYNfmifmm3n3Wbb/4QSMv1xZdP+Wx3CTxzx1ZaX6tmgJLJspfGdiQzeykKv5nQKNCIv+PCkUJHD/X1Ec41YY3N7N5AgW+oDMJ77DfwhHov8lEfw9dfCH2hHNXLxspoDv0KRDmUcZoci5iG3odDojBK2cZGJyUv1s=,iv:iNE1r8UBt3fKxJ5uStRDgbc9q2dIRRsQ7mT2fJP8iok=,tag:sey+qjwGdlf+/7yOxFGTng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
