apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - cors-proxy.yaml
  - ingress.yaml
configMapGenerator:
  - name: cors-proxy
    files:
      - server.js
    literals:
      - allowed-origins=https://edit.gtfs.zone,https://viz.rt.gtfs.zone,http://localhost:8080,http://localhost:8081,http://localhost:8082,http://127.0.0.1:8080,http://127.0.0.1:8081,http://127.0.0.1:8082,http://localhost:8083,http://127.0.0.1:8083,http://localhost:8084,http://127.0.0.1:8084,http://localhost:8085,http://127.0.0.1:8085,http://localhost:8086,http://127.0.0.1:8086,http://localhost:8087,http://127.0.0.1:8087,http://localhost:8088,http://127.0.0.1:8088,http://localhost:8089,http://127.0.0.1:8089,http://localhost:8090,http://127.0.0.1:8090,http://localhost:8091,http://127.0.0.1:8091
