apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami:v1.11.0
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: home
spec:
  selector:
    app: whoami
  ports:
    - port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: home
  annotations:
    external-dns.alpha.kubernetes.io/target: kcfam.us
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`whoami.new.kcfam.us`)
      kind: Rule
      services:
        - name: whoami
          port: 80
  tls:
    secretName: new-kcfam-us-tls
