http:
  services:
    tgtg:
      loadBalancer:
        servers:
          - url: "http://tgtg:3000"

  routers:
    tgtg:
      rule: "Host(`tgtg.kcfam.us`)"
      entryPoints:
        - "websecure"
      tls:
        certResolver: letsencrypt
      service: "tgtg"
