apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
generators:
  - secret-generator.yaml
resources:
  - gatus.yaml
  - ingress.yaml
configMapGenerator:
  - name: gatus-config
    files:
      - config.yaml
