apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-new
  namespace: home
  annotations:
    external-dns.alpha.kubernetes.io/target: kcfam.us
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`gf.new.kcfam.us`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
  tls:
    secretName: new-kcfam-us-tls
---
## gf.kcfam.us's CNAME predates external-dns, so this route carries no target annotation.
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: home
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`gf.kcfam.us`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
  tls:
    secretName: gf-kcfam-us-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gf-kcfam-us-tls
  namespace: home
spec:
  secretName: gf-kcfam-us-tls
  dnsNames:
    - gf.kcfam.us
  issuerRef:
    name: letsencrypt-porkbun
    kind: ClusterIssuer
