apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
generators:
  - secret-generator.yaml
resources:
  - rules.yaml
  - ingress.yaml
configMapGenerator:
  - name: home-server-overview-dashboard
    files:
      - home-server-overview.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
