## Routes to Home Assistant and Music Assistant on Docker.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-docker-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/maxtkc/kcfam-infra.git
    targetRevision: main
    path: home/docker-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: home
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
